steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/karijerko-front:$COMMIT_SHA',
      '--build-arg=VITE_API_BASE_URL=${_VITE_API_BASE_URL}',
      '--build-arg=VITE_GOOGLE_OAUTH_CLIENT_ID=${_VITE_GOOGLE_OAUTH_CLIENT_ID}',
      '.'
    ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/karijerko-front:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'karijerko-front'
      - '--image'
      - 'gcr.io/$PROJECT_ID/karijerko-front:$COMMIT_SHA'
      - '--region'
      - 'europe-west4'
images:
  - 'gcr.io/$PROJECT_ID/karijerko-front:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
